`timescale 1ns / 1ps
`ifndef DEFINTIONS_V
`define DEFINTIONS_V
	
`default_nettype none	
`define NOP   4'd0
`define LED   4'd2
`define BLE   4'd3
`define STO   4'd4
`define ADD   4'd5
`define JMP   4'd6
`define SUB   4'd7   
`define VGA   4'd8
`define LCD   4'd9
`define CALL  4'd10
`define RET   4'd11
`define CPY   4'd12
`define BEAST  4'd13
`define BWEST  4'd14
`define BNORTH  4'd15
`define BSOUTH  4'd1



`define R0 8'd0
`define R1 8'd1
`define R2 8'd2
`define R3 8'd3
`define R4 8'd4
`define R5 8'd5
`define R6 8'd6
`define R7 8'd7

`define STATE_RESET 0
`define STATE_POWERON_INIT_0 1
`define STATE_POWERON_INIT_1 2
`define STATE_POWERON_INIT_2 3
`define STATE_POWERON_INIT_3 4
`define STATE_POWERON_INIT_4 5
`define STATE_POWERON_INIT_5 6
`define STATE_POWERON_INIT_6 7
`define STATE_POWERON_INIT_7 8
`define STATE_POWERON_INIT_8 9
`define STATE_DISPLAY_CONFIG_0 10
`define STATE_DISPLAY_CONFIG_1 11
`define STATE_DISPLAY_CONFIG_2 12
`define STATE_DISPLAY_CONFIG_3 13
`define STATE_DISPLAY_CONFIG_4 14
`define STATE_DISPLAY_CONFIG_5 15
`define STATE_DISPLAY_CONFIG_6 16
`define STATE_DISPLAY_CONFIG_7 17
`define STATE_DISPLAY_CONFIG_8 18
`define STATE_DISPLAY_CONFIG_9 19
`define STATE_DISPLAY_CONFIG_10 20
`define STATE_DISPLAY_CONFIG_11 21
`define STATE_DISPLAY_CONFIG_12 22
`define STATE_DISPLAY_CONFIG_13 23
`define STATE_DISPLAY_CONFIG_14 24
`define STATE_DISPLAY_CONFIG_15 25
`define STATE_DISPLAY_IDLE 25
`define STATE_DISPLAY_WRITE_0 27
`define STATE_DISPLAY_WRITE_1 28
`define STATE_DISPLAY_WRITE_2 29
`define STATE_DISPLAY_WRITE_3 30
`define STATE_DISPLAY_WRITE_4 31
`define STATE_DISPLAY_WRITE_5 32
`define STATE_DISPLAY_WRITE_6 33
`define STATE_DISPLAY_WRITE_7 34

`define BLACK 3'b000
`define BLUE 3'b001
`define GREEN 3'b010
`define CYAN 3'b011
`define RED 3'b100
`define MAGENTA 3'b101
`define YELLOW 3'b110
`define WHITE 3'b111

`define STATE_RESET 0
`define STATE_POWERON_INIT_0 1
`define STATE_POWERON_INIT_1 2
`define STATE_POWERON_INIT_2 3
`define STATE_POWERON_INIT_3 4
`define STATE_POWERON_INIT_4 5
`define STATE_POWERON_INIT_5 6
`define STATE_POWERON_INIT_6 7
`define STATE_POWERON_INIT_7 8
`define STATE_POWERON_INIT_8 9
`define STATE_DISPLAY_CONFIG_0 10
`define STATE_DISPLAY_CONFIG_1 11
`define STATE_DISPLAY_CONFIG_2 12
`define STATE_DISPLAY_CONFIG_3 13
`define STATE_DISPLAY_CONFIG_4 14
`define STATE_DISPLAY_CONFIG_5 15
`define STATE_DISPLAY_CONFIG_6 16
`define STATE_DISPLAY_CONFIG_7 17
`define STATE_DISPLAY_CONFIG_8 18
`define STATE_DISPLAY_CONFIG_9 19
`define STATE_DISPLAY_CONFIG_10 20
`define STATE_DISPLAY_CONFIG_11 21
`define STATE_DISPLAY_CONFIG_12 22
`define STATE_DISPLAY_CONFIG_13 23
`define STATE_DISPLAY_CONFIG_14 24
`define STATE_DISPLAY_CONFIG_15 25
//`define STATE_DISPLAY_IDLE 26
`define STATE_DISPLAY_WRITE_0 27
`define STATE_DISPLAY_WRITE_1 28
`define STATE_DISPLAY_WRITE_2 29
`define STATE_DISPLAY_WRITE_3 30
`define STATE_DISPLAY_WRITE_4 31
`define STATE_DISPLAY_WRITE_5 32
`define STATE_DISPLAY_WRITE_6 33
`define STATE_DISPLAY_WRITE_7 34

`endif
