all: mult1

mult1:	ejercicio_1/mult_test.w
	code_parser.pl -code=ejercicio_1/mult_test.w -out=inputs/Module_ROM.v

mult2:	ejercicio_2/mult_test.w
	code_parser.pl -code=ejercicio_2/mult_test.w -out=inputs/Module_ROM.v

mult3:	ejercicio_3/mult_test.w
	code_parser.pl	-code=ejercicio_3/mult_test.w -out=inputs/Module_ROM.v
