all: mult1

ejercicio1: ejercicio_1/hola_mundo.w
	../scripts/code_parser.pl -code=ejercicio_1/hola_mundo.w -out=inputs/Module_ROM.v

mult2:	ejercicio_2/mult_test.w
	 ../scripts/code_parser.pl -code=ejercicio_2/mult_test.w -out=inputs/Module_ROM.v

mult3:	ejercicio_3/mult_test.w
	 ../scripts/code_parser.pl	-code=ejercicio_3/mult_test.w -out=inputs/Module_ROM.v

mult4:  ejercicio_4/mult_test.w
	../scripts/code_parser.pl      -code=ejercicio_4/mult_test.w -out=inputs/Module_ROM.v

